# Generated by Django 6.0.4 on 2026-04-19 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('licencia', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'choferes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maniobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicita', models.CharField(blank=True, max_length=255, null=True)),
                ('agencia', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_pis', models.CharField(blank=True, max_length=100, null=True)),
                ('terminal', models.CharField(blank=True, max_length=100, null=True)),
                ('placas_pis', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pis', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_peso', models.CharField(blank=True, max_length=255, null=True)),
                ('contenedor', models.CharField(blank=True, max_length=255, null=True)),
                ('pedimento', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('asignacion_operador', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'maniobras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remolque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('placas', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'remolques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_eco', models.CharField(max_length=255, unique=True)),
                ('unidad', models.CharField(max_length=255)),
                ('placas', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tractos',
                'managed': False,
            },
        ),
    ]
