# Generated by Django 6.0.4 on 2026-05-09 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('licencia', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'choferes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega_mercancia', models.CharField(blank=True, max_length=50, null=True)),
                ('casetas_ida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('casetas_regreso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gastos_adicionales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entregado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gasto_tag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gasto_diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comision_operador', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reparaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gastos_totales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('facturado', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_gastos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maniobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicita', models.CharField(blank=True, max_length=255, null=True)),
                ('agencia', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_pis', models.CharField(blank=True, max_length=100, null=True)),
                ('terminal', models.CharField(blank=True, max_length=100, null=True)),
                ('placas_pis', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pis', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_y_peso', models.CharField(blank=True, max_length=255, null=True)),
                ('contenedor', models.CharField(blank=True, max_length=255, null=True)),
                ('pedimento', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('asignacion_operador_status', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('folio', models.CharField(blank=True, max_length=100, null=True)),
                ('vacio_patio', models.CharField(blank=True, max_length=255, null=True)),
                ('status_vacio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrega_mercancia', models.CharField(blank=True, max_length=50, null=True)),
                ('no_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('ccp', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('activo', 'Activo / En viaje'), ('pendiente', 'Pendiente'), ('quemada', 'Quemada'), ('por_salir', 'Por salir')], db_index=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'maniobras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remolque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('placas', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'remolques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_eco', models.CharField(max_length=255, unique=True)),
                ('unidad', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('placas', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tractos',
                'managed': False,
            },
        ),
    ]
