# Generated by Django 6.0.4 on 2026-05-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor', models.CharField(blank=True, max_length=255, null=True)),
                ('patio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_maniobra', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_notificacion_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.CharField(blank=True, max_length=255, null=True)),
                ('cita', models.CharField(blank=True, max_length=255, null=True)),
                ('cd', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vacios',
                'managed': False,
            },
        ),
    ]
