# Generated by Django 6.0.3 on 2026-05-01 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega_mercancia', models.DateField(blank=True, null=True)),
                ('casetas_ida', models.FloatField(blank=True, null=True)),
                ('casetas_regreso', models.FloatField(blank=True, null=True)),
                ('gastos_adicionales', models.FloatField(blank=True, null=True)),
                ('entregado', models.FloatField(blank=True, null=True)),
                ('gasto_tag', models.FloatField(blank=True, null=True)),
                ('gasto_diesel', models.FloatField(blank=True, null=True)),
                ('comision_operador', models.FloatField(blank=True, null=True)),
                ('reparaciones', models.FloatField(blank=True, null=True)),
                ('gastos_totales', models.FloatField(blank=True, null=True)),
                ('facturado_pendiente', models.FloatField(blank=True, null=True)),
                ('maniobra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='api.maniobra')),
            ],
        ),
    ]
