# Generated by Django 6.0.4 on 2026-05-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'managed': False},
        ),
    ]
