# Generated by Django 6.0.3 on 2026-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajador', models.CharField(max_length=255)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('nss', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
