# Generated by Django 6.0.4 on 2026-06-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empleado_patio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patio',
            name='direccion',
        ),
    ]
