# Generated by Django 6.0.4 on 2026-06-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_fotoregistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True, 'ordering': ['nombre_cliente']},
        ),
        migrations.AlterModelOptions(
            name='destino',
            options={'managed': True, 'ordering': ['ciudad']},
        ),
        migrations.AlterModelOptions(
            name='fotoregistro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='origen',
            options={'managed': True, 'ordering': ['ciudad']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fotoregistro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
