# Generated by Django 6.0.4 on 2026-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_tipo_peso_referencia_maniobra_colonia_ciudad_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('operador', models.CharField(blank=True, max_length=255, null=True)),
                ('movimiento', models.CharField(blank=True, max_length=500, null=True)),
                ('unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('contenedor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], db_index=True, default='pendiente', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
