# Generated by Django 6.0.4 on 2026-07-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_maniobra_peso_column_to_varchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('transportista', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=255)),
                ('transportista', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['placas'],
                'managed': True,
            },
        ),
    ]
