# Generated by Django 6.0.4 on 2026-07-23 17:42

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_grant_otp_writes_to_standard_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoConfianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=120)),
                ('ip_alta', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_alta', models.CharField(blank=True, default='', max_length=400)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(default=api.models._caducidad_por_defecto)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_confianza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
    ]
