# Generated by Django 6.0.7 on 2026-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_maniobra_cliente_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(choices=[('manzanillo', 'Folios Manzanillo'), ('lazaro', 'Folios Lázaro C')], db_index=True, max_length=20)),
                ('numero', models.IntegerField()),
                ('letra', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('asignacion', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['tabla', 'numero'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('tabla', 'numero'), name='uniq_folio_tabla_numero')],
            },
        ),
    ]
