# Generated by Django 6.0.8 on 2026-08-20 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_maniobra_ccp_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManiobraCostoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_extra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.costoextra')),
                ('maniobra', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='costos_extra_links', to='api.maniobra')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('maniobra', 'costo_extra'), name='uniq_maniobra_costo_extra')],
            },
        ),
    ]
