# Generated by Django 6.0.8 on 2026-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_grant_costos_extra_to_standard_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablero', models.CharField(choices=[('ali', 'Ali'), ('enrique', 'Enrique'), ('mari', 'Mari'), ('shell', 'Shell'), ('edson', 'Edson')], db_index=True, max_length=20)),
                ('texto', models.CharField(max_length=500)),
                ('hecho', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
