# Generated by Django 6.0.8 on 2026-08-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_maniobra_dd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorreControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveSmallIntegerField(default=1)),
                ('fecha', models.DateField()),
                ('tracto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bolitas', to='api.tracto')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('tracto', 'indice'), name='uniq_torre_control_tracto_indice'), models.CheckConstraint(condition=models.Q(('indice__gte', 1), ('indice__lte', 2)), name='torre_control_indice_1_o_2')],
            },
        ),
    ]
