# Generated by Django 6.0.8 on 2026-08-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_vacio_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorreFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100, unique=True)),
                ('tracto', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='folio_torre', to='api.tracto')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
