# Generated by Django 6.0.8 on 2026-08-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_grant_torrefolio_to_standard_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('coordinador', models.CharField(blank=True, default='', max_length=255)),
                ('servicio', models.CharField(blank=True, default='', max_length=20)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('recoleccion', models.CharField(blank=True, choices=[('propio', 'Propio'), ('tercero', 'Tercero')], default='', max_length=10)),
                ('origen', models.CharField(blank=True, default='', max_length=100)),
                ('destino', models.CharField(blank=True, default='', max_length=100)),
                ('operador', models.CharField(blank=True, default='', max_length=255)),
                ('cita', models.DateTimeField(blank=True, null=True)),
                ('salida_puerto', models.DateTimeField(blank=True, null=True)),
                ('inicio_pactado', models.DateTimeField(blank=True, null=True)),
                ('salida_real', models.DateTimeField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, default='', max_length=100)),
                ('remolque_1', models.CharField(blank=True, default='', max_length=255)),
                ('remolque_2', models.CharField(blank=True, default='', max_length=255)),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('llegada_cliente', models.DateTimeField(blank=True, null=True)),
                ('descarga', models.DateTimeField(blank=True, null=True)),
                ('litros_aceite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_aceite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reparacion', models.BooleanField(null=True)),
                ('reparacion_que', models.CharField(blank=True, default='', max_length=255)),
                ('reparacion_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rescate', models.BooleanField(null=True)),
                ('rescate_unidad', models.CharField(blank=True, default='', max_length=100)),
                ('rescate_operador', models.CharField(blank=True, default='', max_length=255)),
                ('llegada_manzanillo', models.DateTimeField(blank=True, null=True)),
                ('maniobra_vacio', models.BooleanField(null=True)),
                ('patio_entrega', models.CharField(blank=True, default='', max_length=100)),
                ('cita_vacio', models.DateTimeField(blank=True, null=True)),
                ('unidad_vacio', models.CharField(blank=True, default='', max_length=100)),
                ('operador_vacio', models.CharField(blank=True, default='', max_length=255)),
                ('estadias', models.BooleanField(null=True)),
                ('estadias_horas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('litros_diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_litro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('litros_urea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_urea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='api.reporteviaje')),
            ],
            options={
                'ordering': ['orden'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('reporte', 'orden'), name='uniq_carga_reporte_orden'), models.CheckConstraint(condition=models.Q(('orden__gte', 1), ('orden__lte', 5)), name='carga_orden_en_rango')],
            },
        ),
    ]
