# Generated by Django 6.0.8 on 2026-08-24 20:45

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def rellenar(apps, schema_editor):
    """Calcula el rendimiento de los reportes que ya existían.

    Sin esto, un reporte viejo se queda en NULL hasta que alguien vuelva a
    guardarlo — y puede que nadie lo haga nunca. Los informes que vienen después
    lo verían como si no tuviera rendimiento en vez de como lo que es.

    La división se repite aquí en vez de llamar a ReporteViaje.calcular_
    rendimiento(): en una migración el modelo es el HISTÓRICO, sin métodos. Es la
    copia habitual de las migraciones de datos, y no se vuelve a tocar.

    `using=alias` NO es opcional. Sin él, RoleBasedRouter manda estas consultas
    al alias `standard` — OTRA conexión— mientras el AddField de arriba tiene la
    tabla bloqueada desde la conexión de la migración, que sigue en transacción.
    La migración se queda esperándose a sí misma para siempre: comprobado, cuelga
    el `migrate` sin error ni traza. Es la primera migración de DATOS con ORM
    sobre una tabla managed=True de este proyecto; las anteriores (0046, 0050…)
    usan schema_editor.execute() y van por la conexión de la migración solas.
    """
    alias = schema_editor.connection.alias
    ReporteViaje = apps.get_model('api', 'ReporteViaje')
    for reporte in ReporteViaje.objects.using(alias).prefetch_related('cargas'):
        if reporte.km_inicial is None or reporte.km_final is None:
            continue
        litros = sum((c.litros_diesel for c in reporte.cargas.all()
                      if c.litros_diesel is not None), Decimal('0'))
        if not litros:
            continue
        km = reporte.km_final - reporte.km_inicial
        reporte.rendimiento = (Decimal(km) / litros).quantize(
            Decimal('0.01'), rounding=ROUND_HALF_UP)
        reporte.save(using=alias, update_fields=['rendimiento'])


def vaciar(apps, schema_editor):
    """Al revertir, la columna se va entera con el AddField: no hay nada que
    deshacer aquí. Existe para que la migración sea reversible."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_grant_reporte_viaje_to_standard_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteviaje',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.RunPython(rellenar, reverse_code=vaciar),
    ]
