# Generated by Django 6.0.8 on 2026-08-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_gasto_color'),
    ]

    # DIESEL VOLCADO: lo ultimo que el reporte escribio en gastos.gasto_diesel.
    # Es la memoria del volcado, no un dato del viaje: distingue "ese importe lo
    # puse yo" de "lo capturo una persona", que es lo que permite dejar de pisar
    # el trabajo manual sin romper el llenado por etapas del reporte.
    #
    # `reportes_viaje` SI es managed=True (la creo la 0051), asi que el AddField
    # genera el ALTER TABLE por si mismo: aqui no hace falta RunSQL como en las
    # tablas heredadas.
    #
    # Nullable y sin default: los reportes que ya existen no han volcado nada
    # bajo esta regla, y NULL dice exactamente eso. Con 0 diriamos "volco cero",
    # que protegeria un importe capturado a mano que valiera 0.
    operations = [
        migrations.AddField(
            model_name='reporteviaje',
            name='diesel_volcado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
