# Generated by Django 6.0.8 on 2026-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_vacio_cita_fecha_hora'),
    ]

    # CON CITA: que patios exigen una hora concreta para recibir el vacio. El
    # resto reciben a cita abierta, y de ahi sale el "CITA ABIERTA" que la
    # columna CITA de Vacios enseña sola.
    #
    # `api_patio` es managed=True, asi que el AddField genera su propio ALTER
    # TABLE — no hace falta el RunSQL de las tablas heredadas. El GRANT de la
    # 0005 es a nivel de TABLA, asi que la columna nueva entra ya cubierta.
    #
    # default=False y no True: los patios que ya existen no se marcaron nunca,
    # y arrancar en "exige cita" pondria a todos en el estado que hay que
    # capturar a mano, que es justo lo que se quiere evitar.
    operations = [
        migrations.AddField(
            model_name='patio',
            name='con_cita',
            field=models.BooleanField(default=False),
        ),
        # El DEFAULT se queda en la BASE, y Django lo quita despues de rellenar
        # las filas que ya estaban. Se vuelve a poner porque esta migracion corre
        # ANTES de desplegar: durante esos minutos el codigo VIEJO sigue vivo en
        # produccion y da de alta patios sin esta columna. Sin default en la base
        # ese INSERT choca con el NOT NULL y da un 500 al agregar un patio.
        migrations.RunSQL(
            sql="ALTER TABLE api_patio ALTER COLUMN con_cita SET DEFAULT false;",
            reverse_sql="ALTER TABLE api_patio ALTER COLUMN con_cita DROP DEFAULT;",
        ),
    ]
