# Generated by Django 6.0.8 on 2026-09-14 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_nomina_y_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteviaje',
            name='km_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reporteviaje',
            name='km_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
