# Generated by Django 6.0.8 on 2026-10-06 23:37

import django.db.models.deletion
from django.db import migrations, models

# Historial de sueldos para la utilidad (usuario, 2026-10-06; PENDIENTE §13).
#
# Sin GRANT a django_standard_role, a proposito y por lo mismo que la 0067: son
# sueldos. La API y el /admin los leen como `default`.
#
# Los sueldos que ya existen entran con `desde` null = desde siempre, asi que la
# utilidad de los meses pasados no se mueve al aplicar esto.


def sembrar(apps, schema_editor):
    # using= explicito: sin el, el router manda las escrituras a 'standard' y el
    # migrate se queda colgado esperando el bloqueo de la tabla recien creada.
    alias = schema_editor.connection.alias
    Nomina = apps.get_model('api', 'NominaEmpleado')
    Historial = apps.get_model('api', 'SueldoHistorial')
    Historial.objects.using(alias).bulk_create(
        Historial(empleado_id=n.empleado_id, sueldo=n.sueldo, desde=None)
        for n in Nomina.objects.using(alias).filter(sueldo__isnull=False))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_cargas_decimales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SueldoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desde', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(db_column='empleado_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sueldos', to='api.empleado')),
            ],
            options={
                'verbose_name_plural': 'historial de sueldos',
                'ordering': ['empleado_id', 'desde'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('empleado', 'desde'), name='sueldo_unico_por_dia')],
            },
        ),
        migrations.RunPython(sembrar, migrations.RunPython.noop),
    ]
