"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "La variable de entorno DJANGO_SECRET_KEY debe estar definida. "
        "Genera una con: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,::1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'api.Apps.ApiConfig',
    'corsheaders',
    'django_filters',
    'axes',
    # MFA para cuentas admin (decisión A4). otp_totp = códigos de 6 dígitos que
    # rotan cada 30s; otp_static = códigos de respaldo de un solo uso para
    # recuperar el acceso si se pierde el teléfono (manage.py addstatictoken).
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise va justo después de SecurityMiddleware y antes que todo lo
    # demás: sirve los estáticos sin pasar por el resto de la cadena.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # IPRateLimitMiddleware eliminado (3.1.5): leía la posición del XFF que
    # escribe el cliente y su diccionario crecía sin límite. Ver api/middleware.py.
    'api.middleware.RoleRoutingMiddleware',
    'api.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Tiene que ir DESPUÉS de AuthenticationMiddleware: añade request.user.is_verified().
    # Por sí solo no exige nada; el enforce sobre /admin se activa aparte (3.3.5).
    'django_otp.middleware.OTPMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# ── Security settings ───────────────────────────────────────────────────────

# Django agrega X-Content-Type-Options: nosniff de forma nativa
SECURE_CONTENT_TYPE_NOSNIFF = True

# Django agrega X-Frame-Options: DENY de forma nativa
X_FRAME_OPTIONS = 'DENY'

# En Django 4+, SECURE_BROWSER_XSS_FILTER es obsoleto y False es correcto
SECURE_BROWSER_XSS_FILTER = False

# ── Configuración de producción — se ACTIVA sola con DEBUG=False ────────────
# En desarrollo (DEBUG=True) quedan inactivas para no romper http://localhost.
# En producción (DEBUG=False) Django las aplica todas. El redirect a HTTPS y la
# emisión de HSTS los hace django.middleware.security.SecurityMiddleware.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000            # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Azure Container Apps termina TLS en su ingress y reenvía X-Forwarded-Proto.
    # Sin esta línea, SECURE_SSL_REDIRECT entra en bucle de redirección infinito.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS — Origins permitidos leídos desde variable de entorno
# Formato en .env: CORS_ALLOWED_ORIGINS=http://localhost:3000,https://tudominio.com
_cors_origins_raw = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000')
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in _cors_origins_raw.split(',')
    if origin.strip()
]

# Reutiliza los mismos orígenes para la protección CSRF de Django
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# NUNCA usar CORS_ALLOW_ALL_ORIGINS = True

# JWT viaja en header Authorization, no en cookies → credentials False
CORS_ALLOW_CREDENTIALS = False

# Solo los métodos que usa la API
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Headers mínimos necesarios para el frontend React + JWT
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Tiempo que el navegador cachea la respuesta preflight OPTIONS
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 horas

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Cerrado por defecto. Sin esta línea DRF usa AllowAny, y 11 viewsets que no
    # declaraban permission_classes servían datos a peticiones anónimas (maniobras,
    # gastos, vacios, choferes, tractos, remolques, empleados, patios, clientes,
    # origenes, destinos) — lectura Y escritura, al ser ModelViewSet.
    # Ahora hay que abrir a propósito, no cerrar por acordarse.
    # Login y refresh siguen siendo públicos sin tocarlos: SimpleJWT los declara
    # con permission_classes = () en TokenViewBase, que gana a este valor por defecto.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Los de DRF sin tocar usan la cadena X-Forwarded-For ENTERA como clave, así
    # que cualquier valor distinto abría un cubo nuevo y el límite no existía.
    # Estos identifican por la IP real medida. Ver api/throttling.py.
    "DEFAULT_THROTTLE_CLASSES": [
        "api.throttling.AnonIpRealThrottle",   # usuarios sin login
        "api.throttling.UserIpRealThrottle",   # usuarios autenticados
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/minute",   # máximo 30 peticiones por minuto sin login
        "user": "200/minute",  # máximo 200 peticiones por minuto con login
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 60,  # cambiado de 30 a 60
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "EXCEPTION_HANDLER": "api.utils.custom_exception_handler",
}

# JWT: sessionStorage borra los tokens al cerrar el navegador y el timer de
# inactividad cierra la sesión a los 20 min. El access dura poco (limita el daño
# de un token robado); el refresh dura la jornada y el interceptor 401 del
# frontend renueva el access sin interrumpir al usuario. El logout invalida el
# refresh vía blacklist (rest_framework_simplejwt.token_blacklist).
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=12),
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Conexión de superuser: usada por admin y por migraciones
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_ADMIN_USER'),
        'PASSWORD': os.environ.get('DB_ADMIN_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # Reutiliza la conexión hasta 60s en vez de cerrarla al final de cada
        # request — evita el costo de reconectar+autenticar contra Postgres
        # en cada petición. No afecta RoleBasedRouter ni las políticas RLS.
        'CONN_MAX_AGE': 60,
    },
    'standard': {
        # Conexión de rol estándar: usada por usuarios no-admin
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_STANDARD_USER'),
        'PASSWORD': os.environ.get('DB_STANDARD_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
    },
}

DATABASE_ROUTERS = ['api.routers.RoleBasedRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Estáticos servidos por WhiteNoise dentro del contenedor. Son SOLO los de
# /admin y DRF: el SPA lo sirve Static Web Apps aparte (decisión E2), aquí no
# se compila nada de React. collectstatic los junta en STATIC_ROOT durante el
# build de la imagen.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CompressedManifestStaticFilesStorage: comprime y añade hash al nombre, así los
# estáticos del admin pueden cachearse para siempre sin servir versiones viejas.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ── Autenticación (django-axes) ─────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ── django-axes (brute force protection) ───────────────────────────────────
# Sin esto axes usa REMOTE_ADDR, que detrás de App Service es SIEMPRE la IP
# interna del front-end (169.254.x.x): la misma para todo el mundo. Con
# AXES_LOCKOUT_PARAMETERS = [['username','ip_address']] eso degeneraba en
# bloquear solo por usuario, y CUALQUIERA podía dejar fuera a cualquiera
# fallando 5 veces con su nombre. Con la IP real, el atacante solo se bloquea
# a sí mismo y el usuario legítimo entra sin enterarse.
# Se usa el callable en vez de AXES_IPWARE_*: ipware NO está instalado, así que
# esos ajustes no habrían tenido ningún efecto (verificado en vivo).
AXES_CLIENT_IP_CALLABLE = 'api.client_ip.client_ip'

AXES_FAILURE_LIMIT = 5          # Bloqueo después de 5 intentos fallidos
AXES_COOLOFF_TIME = 1           # Tiempo de bloqueo: 1 hora
AXES_RESET_ON_SUCCESS = True    # Resetea contador al login exitoso
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]  # Bloquea por user+IP
AXES_ENABLE_ADMIN = True        # Visible en el panel admin de Django
AXES_VERBOSE = False            # No loguear cada intento en consola

# ── MFA / TOTP (django-otp) ─────────────────────────────────────────────────
# ponytail: django-otp reaprende y PERSISTE el `drift` (desfase móvil↔servidor)
# en cada verificación correcta. Un contenedor con el reloj torcido fosiliza ese
# drift en la BD y bloquea a TODOS en el siguiente redeploy (incidente 2026-07-23,
# arreglado a mano con psql). Con SYNC=False el drift nunca se guarda: un reloj
# malo, si acaso, causa un fallo temporal que se auto-cura al redesplegar, sin
# tocar la BD. El anti-reuso lo sigue dando `last_t`, que se guarda igual.
# El `tolerance` de cada dispositivo (piso de 2 = ±60s, ver api/Apps.py) absorbe
# el desfase modesto entre contenedores de Azure.
OTP_TOTP_SYNC = False

# Configuración de Logs físicos para errores del sistema (Jira Task)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'clear_format': {
            'format': '[{levelname}] {asctime} {module} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        # stdout: en contenedor la plataforma captura la salida; un archivo local
        # se perdería en cada deploy. En dev se ve en la consola de runserver.
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'clear_format',
        },
        # Handler propio a INFO: los eventos de seguridad son esperados, no
        # fallos, y el handler de errores está en ERROR y se los tragaría.
        'console_security': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'clear_format',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'api': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        # Eventos de seguridad (3.4.2): login OK/fallido, lockouts de axes y
        # accesos denegados 401/403. propagate=False para que no se dupliquen
        # a través del logger padre 'api'.
        'api.security': {
            'handlers': ['console_security'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
